=== ibq-daw1-1920-16/lmsgi/Unidad_04/informaAlumno.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:simpleType name="Decimal10-2">
    <xs:restriction base="xs:decimal">
        <xs:maxInclusive value="9999999999" />
        <xs:fractionDigits value="2"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="No-presentado">
    <xs:restriction base="xs:string">
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="OptionalDecimal10-2">
    <xs:union memberTypes="Decimal10-2 No-presentado" />
  </xs:simpleType>

<xs:attributeGroup name="Datos">
    <xs:attribute name="dni" type="xs:string"/>
    <xs:attribute name="calle" type="xs:string"/>
    <xs:attribute name="numero" type="xs:string"/>
    <xs:attribute name="piso" type="xs:string"/>
    <xs:attribute name="poblacion" type="xs:string"/>
    <xs:attribute name="Codigo-postal" type="xs:string"/>
</xs:attributeGroup>




<xs:element name="informaAlumno" >

<xs:complexType>
    <xs:sequence>
<xs:element name="alumno" minOccurs="1" maxOccurs="unbounded">

    <xs:complexType>
        <xs:sequence>
        <xs:element name="nombre"/>
        <xs:element name="apellidos"/>
        <xs:element name="nota" type="OptionalDecimal10-2"/>
        <xs:element name="edad"/>
        
        <xs:element name="comentario" type="xs:string"/>
        </xs:sequence>
        <xs:attributeGroup ref="Datos" />

        
    </xs:complexType>

</xs:element>
</xs:sequence>
</xs:complexType>

</xs:element>
</xs:schema>

=== ibq-daw1-1920-16/lmsgi/Unidad_04/PrimerXML_04.xml
<?xml version="1.0" encoding="UTF-8" ?>

<informaAlumno  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="informaAlumno.xsd">

    <alumno dni="99887766X" >
        <nombre>Dario</nombre>
        <apellidos>Fernández Álvarez</apellidos>
        <nota>3.50</nota>
        <edad>45</edad>
        <comentario>Necesita mejorar</comentario>
    </alumno>

    <alumno dni="11223344A" >
        <nombre>Luis</nombre>
        <apellidos>Álvarez García</apellidos>
        <nota>6.75</nota>
        <edad>80</edad>
        <comentario>Copio de Dario, Alfredo y Pilar</comentario>
    </alumno>

 
    <alumno dni="556677Z" >
        <nombre>Pilar</nombre>
        <apellidos>Rodríguez Menéndez</apellidos>
        <nota>8.25</nota>
        <edad></edad>
        <comentario>Copio de todos</comentario>
    </alumno>

    
    <alumno dni="66554433T" >
        <nombre>Alfredo</nombre>
        <apellidos>Martínez González</apellidos>
        <nota>No presentado</nota>
        <edad>42</edad>
        <comentario>Copio de todos</comentario>
    </alumno>

</informaAlumno>
